sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t vrmarine/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true vrmarine/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-730690868697"
  bucket_path: "docker-react-app"
  on:
    branch: main
  access_key_id: \$AWS_ACCESS_KEY_docker-react-app
  secret_access_key: \$AWS_SECRET_ACCESS_KEY_docker-react-app